const IMAGES = {
    image1: require('../assets/images/image1.png'),
    image2: require('../assets/images/image2.png'),
    image3: require('../assets/images/image3.png'),
    image4: require('../assets/images/image4.png'),
    image5: require('../assets/images/image5.png'),
    image6: require('../assets/images/image6.png'),
    image7: require('../assets/images/image7.png'),
    image8: require('../assets/images/image8.png'),
    image9: require('../assets/images/image9.png'),
    image10: require('../assets/images/image10.png'),
    image11: require('../assets/images/image11.png'),
    image12: require('../assets/images/image12.png'),
    image13: require('../assets/images/image13.png'),
    image14: require('../assets/images/image14.png'),
    choco1: require('../assets/images/choco1.png'),
    choco2: require('../assets/images/choco2.png'),
    choco3: require('../assets/images/choco3.png'),
    choco4: require('../assets/images/choco4.png'),
    choco5: require('../assets/images/choco5.png'),
    choco6: require('../assets/images/choco6.png'),
    choco7: require('../assets/images/choco7.png'),
    choco8: require('../assets/images/choco8.png'),
    choco9: require('../assets/images/choco9.png'),
    choco10: require('../assets/images/choco10.png'),
    choco11: require('../assets/images/choco11.png'),
    choco12: require('../assets/images/choco12.png'),
    choco13: require('../assets/images/choco13.png'),
    buttonBg1: require('../assets/images/buttonBg1.png'),
    buttonBg2: require('../assets/images/buttonBg2.png'),
    buttonBg3: require('../assets/images/buttonBg3.png'),
    btnBg1: require('../assets/images/btn-bg1.png'),
    btnBg2: require('../assets/images/btn-bg2.png'),
    btnBg3: require('../assets/images/btn-bg3.png'),
    grid: require('../assets/images/01.png'),
}

export default {
    IMAGES
}