const IMAGES = {
    image1: require('../assets/images/image1.png'),
    image2: require('../assets/images/image2.png'),
    image3: require('../assets/images/image3.png'),
    image4: require('../assets/images/image4.png'),
    image5: require('../assets/images/image5.png'),
    image6: require('../assets/images/image6.png'),
    image7: require('../assets/images/image7.png'),
    image8: require('../assets/images/image8.png'),
    image9: require('../assets/images/image9.png'),
    image10: require('../assets/images/image10.png'),
    image11: require('../assets/images/image11.png'),
    image12: require('../assets/images/image12.png'),
    image13: require('../assets/images/image13.png'),
    image14: require('../assets/images/image14.png'),
    choco1: require('../assets/images/choco1.png'),
    choco2: require('../assets/images/choco2.png'),
    choco3: require('../assets/images/choco3.png'),
    choco4: require('../assets/images/choco4.png'),
    choco5: require('../assets/images/choco5.png'),
    choco6: require('../assets/images/choco6.png'),
    choco7: require('../assets/images/choco7.png'),
    choco8: require('../assets/images/choco8.png'),
    choco9: require('../assets/images/choco9.png'),
    choco10: require('../assets/images/choco10.png'),
    choco11: require('../assets/images/choco11.png'),
    choco12: require('../assets/images/choco12.png'),
    choco13: require('../assets/images/choco13.png'),
    buttonBg1: require('../assets/images/buttonBg1.png'),
    buttonBg2: require('../assets/images/buttonBg2.png'),
    buttonBg3: require('../assets/images/buttonBg3.png'),
    btnBg1: require('../assets/images/btn-bg1.png'),
    btnBg2: require('../assets/images/btn-bg2.png'),
    btnBg3: require('../assets/images/btn-bg3.png'),
    grid: require('../assets/images/01.png'),
    moon: require('../assets/images/moon.png'),
    sun: require('../assets/images/sun.png'),
    messageBox: require('../assets/images/messageBox.png'),
    verify_success: require('../assets/images/verify_success.png'),
    avatarGirl1: require('../assets/images/avatar/avatar_g_1.png'),
    avatarGirl2: require('../assets/images/avatar/avatar_g_4.png'),
    avatarGirl3: require('../assets/images/avatar/avatar_g_2.png'),
    avatarGirl4: require('../assets/images/avatar/avatar_g_5.png'),
    avatarGirl5: require('../assets/images/avatar/avatar_g_3.png'),
    avatarGirl6: require('../assets/images/avatar/avatar_g_6.png'),
    avatarMan1: require('../assets/images/avatar/avatar_m_1.png'),
    avatarMan2: require('../assets/images/avatar/avatar_m_4.png'),
    avatarMan3: require('../assets/images/avatar/avatar_m_2.png'),
    avatarMan4: require('../assets/images/avatar/avatar_m_5.png'),
    avatarMan5: require('../assets/images/avatar/avatar_m_3.png'),
    avatarMan6: require('../assets/images/avatar/avatar_m_6.png'),
}

export default {
    IMAGES
}